module standardization
viam-labs/viam-face-identification pull request #32
Opened 2024-07-18 17:25 UTC by Rob1in

2024-07-18 17:33 UTC, Rob1in commented
I will convert it to not a draft after testing the requirements on linux/amd

2024-07-18 18:35 UTC, Rob1in commented
tested the build on linux/amd

2024-07-18 18:53 UTC, bhaney reviewed
nice job with the edits, just a question about a name -- if it's a breaking change to change the name of the distance function, then we shouldn't do it.

2024-07-18 18:53 UTC, bhaney commented on src/distance.py
> +    Computes the Euclidean distance between two tensors using the L1 norm.
Euclidean usually means the L2 norm, not L1 -- the L1 norm is colloquially called the "manhattan" or "taxicab" norm

2024-07-18 18:53 UTC, bhaney commented on src/models/utils.py
> +    if distance_metric == "cosine":
Not sure if it's a breaking change to change the name from euclidean to another name to make it more clear that it is the L1 norm, but if it isn't a breaking change, I would save change the name to "l1_norm" or something similar

2024-07-25 18:37 UTC, bhaney requested changes
Almost done, I think you just need to eliminate some of the ignored pylint codes, and then it should be good

2024-07-25 18:37 UTC, bhaney commented on Makefile
> +	python3 -m pylint src --disable=W0719,C0114,W0201,W1203,E1101,W1203,E0611,R0902,R0913,E0611,E0001,R0914,R0903
C0114: Missing module docstring
W0201: Attribute defined outside init
W1203: Use % formatting in logging functions and pass the % parameters as arguments
E1101: Instance of 'x' has no 'y' member
E0611: No name 'x' in module 'y'
E0001: Syntax error
R0801: Similar lines in 'x' files

Remove these from the disable string, and if you do need to disable them, put the ignore right next to the code where you need it

2024-08-06 16:59 UTC, bhaney approved these changes
LGTM!

2024-08-09 09:57 UTC, merged